### ISSUE TITLE
3DMatch dataset with GT Poses

### ISSUE THREAD

**Issue by yuvalH9** [torch-points3d/torch-points3d#714]
Hi,
I'm trying to generate the 3DMatch dataset using `General3DMatchDataset` and the parameters in `fragment3dmatch_dense.yaml`.
As I can see, the generated fragments are enumerated each time a new fragment satisfying the conditions (minimal overlap for example) is found. 

The problem is that the generated dataset in the folder `processed/train/fragment`  has fragments numbers that are not related anymore to the original raw fragments with their corresponding GT poses.txt, and I cant connect a generated `.pt` fragment with its GT pose.

My question is if there is a way to generated the 3DMatch point cloud dataset from the RGBD images using `General3DMatchDataset` and keep for each generated point cloud its GT pose.txt file?

Thanks
Yuval

**Comment by humanpose1** [comment]
Hi @yuvalH9 , 

We do not keep the ground truth poses of the RGBD frames because the pose are used to build the fragments(We use [this function](https://github.com/torch-points3d/torch-points3d/blob/68795cc1869c4ac5de2b81bafe09260d6125cfba/torch_points3d/datasets/registration/base3dmatch.py#L202) to build the fragment that use the GT pose).  Therefore, we do not need the pose anymore because every fragment are already in the same reference.

But if you want to keep the GT poses of the RGBD images, I think you can modify [this function](https://github.com/torch-points3d/torch-points3d/blob/68795cc1869c4ac5de2b81bafe09260d6125cfba/torch_points3d/datasets/registration/utils.py#L214) to keep the pose. But you will need to find a way to derive the pose of the fragment from the poses of the RGBD frames.

I hope I was clear.
Best,

**Comment by yuvalH9** [comment]
@humanpose1 thanks for answering!

Just to be clear, what I want to do is estimate the transformation between `fragment_i` and `fragment_j` of the same scene which is just the camera movement from `i` to `j` (since the scene is static and only the camera travels in the room).
If I understand correctly, to get the relative transformation from `i` to `j`, given the GT poses (in camera to world),  it should be `T_i * inv(T_j)`.
So, besides saving for each valid pair of matched fragments (i.e. two fragments with overlap >30%), their `pose.txt` files (or the relative transformation between them) do I need to consider other things?

thanks,
Yuval
