### ISSUE TITLE
Scannet-fixed Segmentation: No forward will be run on dataset test.

### ISSUE THREAD

**Issue by thzou** [torch-points3d/torch-points3d#740]
Segmentation task: I am trying to get the PointNet++ model evaluated on the test set after the training+validation stages using the scannet-fixed dataset. Unfortunately, after a lot of searching in the configs etc, I am still getting "No forward will be run on dataset test." after each epoch. However, everything works fine with the shapenet fixed dataset. In the case of shapenet-fixed, my output after each epoch is evaluation results on training+validation+test sets. 

Is there a specific configuration setting hidden somewhere?!

**Comment by CCInc** [comment]
Hi, I believe this is because there are no labels for the scannet test split, so torch points does not run them by default (there would be no useful metrics without labels). If you want to output submission labels for you to upload to the scannet benchmark, you can do so using the `make_submission` config option ( see scannet_segmentation_tracker.py for more info).

**Comment by CCInc** [comment]
Closing for now let me know if you need further help!
